// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkvgmremfcnyadptgsxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxrdmdtcmVtZmNueWFkcHRnc3h4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExNTYzNjgsImV4cCI6MjA2NjczMjM2OH0.a5JVSZGGEKD1WJ3phTYtO1Y2VxTMpo6UNsCM0qfCIK8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);